PIPELINE CI/CD:
name: Build and deploy container app to Azure Web App - webappsentimentanalysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://containerregistrysentimentanalysis.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_cfb9154696014248b20687969dca0192 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_480373136ec140299edb42c3445704fe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: containerregistrysentimentanalysis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cfb9154696014248b20687969dca0192 }}/apisentimentanalysis:${{ github.sha }}
        file: ./Dockerfile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run tests
      run: |
        python -m unittest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappsentimentanalysis'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c801e5d7ed11479b971b444f712788f4 }}
        images: 'containerregistrysentimentanalysis.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_cfb9154696014248b20687969dca0192 }}/apisentimentanalysis:${{ github.sha }}'
